{% set version = "1.0" %}

package:
  name: xgeo
  version: {{ version }}

source:
  url: https://github.com/Geosynopsis/xgeo/archive/xgeo-v{{ version }}.tar.gz
  sha256: 2b494a56c8f91967828c49806a0e8cdde2f4af8c24bc2b2ede509ce6ff96a7dc

build:
  number: 1
  noarch: python
  script:  "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pandas >=0.24.1
    - xarray >=0.11.3
    - rasterio >=1.0.18
    - geopandas >=0.4.0
    - netCDF4 >=1.4.2
    - shapely >=1.6.4

test:
  requires:
    - python {{ python_min }}
  imports:
    - xarray
    - xgeo

about:
  home: https://geosynopsis.github.io/xgeo
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Geospatial utility functions using xarray and rasterio
  doc_url: https://geosynopsis.github.io/xgeo

extra:
  recipe-maintainers:
    - geosynopsis
