travis:
  secure:
    BINSTAR_TOKEN: 4mu/dCB8VQGGARDdoDE4iHV6vqwsTK7kGwQmCD5B1qY5MZJ4pRMIySPAj4eRsd417OyEjIkbh8eoElvVd8xs4kP9MJY21sE1jL+o5phWqOJQYosKFqyY/D1qIp+tzv/pV3Fg/EUIL9w0iZrfc6RTg0E8ES0JPbsReTU8YscKHdEDm5qdcmB98xuEKwTeH48Q5Wer/Sqy+eFhEkQ1vpR0jFidH9Qyo1UPmtyEbwIiLo2+h80htoeO2mZ+34dHLFlDecJU2rs2kcOW9/kRdTmUPDAdim3b7eg1QbSa7VuAUlMqpq6cPmUhRwCPnUPJXiJjeuqHXcFeGPDwFgSJ8CwYr1m9r/pDuhAiSmIwAiXhIqyMdkSEdSrUoWen6tGTKMHc5srxJSRDOl3ibYaYNVoRwtOF0iPZnJDysah0Cz4WXXwURIEEttVmq7C8Gu5PVswbmvVnRJI49d6iaf4Ov08+PPafT+DR5mETeg3qVRM0bEIy91L8X4a1qgcuB1N5DmuoOKPd5tIzE5OUdCo2dhq/DaqIyoxlDSwvZeqRYCXMbGF1u2lZF2Ukk3f6zp+6DenBuxSqfzuvmODyHtH9BxCxQdx6eZgwIRVPsokeSV6U0NnqakWRKGDlqyME6expVt0IjpuLi07SONZ7LluEJ+QCR4HH3uWvb9Ce+TzdjKzkhis=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
